"""HTML report generator for validation results."""

from datetime import datetime
from typing import Optional
from pathlib import Path

from src.core.models import ValidationResult, ValidationIssue, Severity


class ReportGenerator:
    """Generate professional HTML validation reports."""
    
    HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YAML Validation Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin-bottom: 10px; }
        .header .meta { opacity: 0.9; font-size: 14px; }
        .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }
        .summary-card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .summary-card.success { border-left: 4px solid #10b981; }
        .summary-card.failure { border-left: 4px solid #ef4444; }
        .summary-card.warning { border-left: 4px solid #f59e0b; }
        .summary-card .number { font-size: 36px; font-weight: bold; }
        .summary-card .label { color: #666; font-size: 14px; }
        .section { background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; overflow: hidden; }
        .section-header { padding: 15px 20px; background: #f8f9fa; border-bottom: 1px solid #eee; font-weight: 600; }
        .issue { padding: 15px 20px; border-bottom: 1px solid #eee; }
        .issue:last-child { border-bottom: none; }
        .issue-header { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
        .issue-code { font-family: monospace; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
        .issue-code.error { background: #fee2e2; color: #dc2626; }
        .issue-code.warning { background: #fef3c7; color: #d97706; }
        .issue-path { color: #666; font-family: monospace; font-size: 13px; }
        .issue-message { margin-bottom: 8px; }
        .issue-suggestion { background: #f0fdf4; padding: 10px; border-radius: 4px; font-size: 14px; color: #166534; }
        .issue-suggestion::before { content: "💡 "; }
        .issue-line { font-size: 12px; color: #666; }
        .code-context { background: #1e1e1e; color: #d4d4d4; padding: 15px; border-radius: 4px; font-family: monospace; font-size: 13px; overflow-x: auto; margin: 10px 0; }
        .code-line { display: flex; }
        .code-line.highlight { background: rgba(239, 68, 68, 0.2); }
        .code-line-num { color: #666; width: 40px; text-align: right; padding-right: 15px; user-select: none; }
        .code-line-content { flex: 1; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>YAML Validation Report</h1>
        <div class="meta">
            <div>File: {filename}</div>
            <div>Generated: {timestamp}</div>
            {profile_info}
        </div>
    </div>
    
    <div class="summary">
        <div class="summary-card {status_class}">
            <div class="number">{status_icon}</div>
            <div class="label">{status_text}</div>
        </div>
        <div class="summary-card {error_class}">
            <div class="number">{error_count}</div>
            <div class="label">Errors</div>
        </div>
        <div class="summary-card {warning_class}">
            <div class="number">{warning_count}</div>
            <div class="label">Warnings</div>
        </div>
    </div>
    
    {errors_section}
    {warnings_section}
    
    <div class="footer">
        Generated by YAML Schema Validator
    </div>
</body>
</html>'''
    
    def generate(
        self,
        result: ValidationResult,
        yaml_text: Optional[str] = None,
        filename: str = "config.yaml",
        profile: Optional[str] = None
    ) -> str:
        """Generate HTML report."""
        
        # Status
        status_class = "success" if result.success else "failure"
        status_icon = "✅" if result.success else "❌"
        status_text = "Passed" if result.success else "Failed"
        
        # Profile info
        profile_info = f"<div>Profile: {profile}</div>" if profile else ""
        
        # Error/warning classes
        error_class = "failure" if result.error_count > 0 else "success"
        warning_class = "warning" if result.warning_count > 0 else "success"
        
        # Generate sections
        errors_section = self._generate_issues_section(
            "Errors", result.errors, yaml_text, "error"
        ) if result.errors else ""
        
        warnings_section = self._generate_issues_section(
            "Warnings", result.warnings, yaml_text, "warning"
        ) if result.warnings else ""
        
        return self.HTML_TEMPLATE.format(
            filename=filename,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            profile_info=profile_info,
            status_class=status_class,
            status_icon=status_icon,
            status_text=status_text,
            error_class=error_class,
            warning_class=warning_class,
            error_count=result.error_count,
            warning_count=result.warning_count,
            errors_section=errors_section,
            warnings_section=warnings_section
        )
    
    def _generate_issues_section(
        self,
        title: str,
        issues: list,
        yaml_text: Optional[str],
        issue_type: str
    ) -> str:
        """Generate HTML section for issues."""
        issues_html = []
        
        for issue in issues:
            code_context = ""
            if issue.line and yaml_text:
                code_context = self._generate_code_context(yaml_text, issue.line)
            
            suggestion_html = ""
            if issue.suggestion:
                suggestion_html = f'<div class="issue-suggestion">{issue.suggestion}</div>'
            
            line_html = ""
            if issue.line:
                line_html = f'<div class="issue-line">Line {issue.line}</div>'
            
            issues_html.append(f'''
            <div class="issue">
                <div class="issue-header">
                    <span class="issue-code {issue_type}">{issue.code}</span>
                    <span class="issue-path">{issue.format_path()}</span>
                </div>
                <div class="issue-message">{issue.message}</div>
                {code_context}
                {suggestion_html}
                {line_html}
            </div>
            ''')
        
        return f'''
        <div class="section">
            <div class="section-header">{title} ({len(issues)})</div>
            {"".join(issues_html)}
        </div>
        '''
    
    def _generate_code_context(self, yaml_text: str, line: int, context: int = 2) -> str:
        """Generate code context HTML."""
        lines = yaml_text.splitlines()
        start = max(0, line - context - 1)
        end = min(len(lines), line + context)
        
        code_lines = []
        for i in range(start, end):
            line_num = i + 1
            is_error = line_num == line
            highlight_class = " highlight" if is_error else ""
            
            # Escape HTML
            content = lines[i].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            
            code_lines.append(
                f'<div class="code-line{highlight_class}">'
                f'<span class="code-line-num">{line_num}</span>'
                f'<span class="code-line-content">{content}</span>'
                f'</div>'
            )
        
        return f'<div class="code-context">{"".join(code_lines)}</div>'
    
    def save(
        self,
        result: ValidationResult,
        output_path: str,
        yaml_text: Optional[str] = None,
        filename: str = "config.yaml",
        profile: Optional[str] = None
    ):
        """Generate and save HTML report to file."""
        html = self.generate(result, yaml_text, filename, profile)
        Path(output_path).write_text(html)


def generate_report(
    result: ValidationResult,
    yaml_text: Optional[str] = None,
    filename: str = "config.yaml",
    profile: Optional[str] = None
) -> str:
    """Generate HTML report string."""
    generator = ReportGenerator()
    return generator.generate(result, yaml_text, filename, profile)